version: "3.8"
services:

  api:
    build:
      context: ../api
      dockerfile: Dockerfile
    env_file:
      - ../.env
    ports:
      - "4000:4000"
    volumes:
      - ../api:/app
    depends_on:
      - orchestrator

  orchestrator:
    build:
      context: ../orchestrator
      dockerfile: Dockerfile
    env_file:
      - ../.env
    ports:
      - "5000:5000"
    volumes:
      - ../orchestrator:/app
    depends_on:
      - api
      - ai-insights

  ai-insights:
    build:
      context: ../orchestrator/ai-insights
      dockerfile: Dockerfile
    env_file:
      - ../.env
    ports:
      - "8100:8100"
    volumes:
      - ../orchestrator/ai-insights:/app

  dashboard:
    build:
      context: ../dashboard
      dockerfile: Dockerfile
    env_file:
      - ../.env
    ports:
      - "3000:3000"
    volumes:
      - ../dashboard:/app
    depends_on:
      - api
