# foundry.toml
# Foundry configuration for building, testing, and fuzzing your Solidity contracts.

[default]
src = "contracts"
out = "out"
libs = ["node_modules/@openzeppelin/contracts"]
tests = "test"
solc_version = "0.8.17"
optimizer = true
optimizer_runs = 200
fork_url = "${MAINNET_RPC_URL}"
rpc_endpoints = { mainnet = "${MAINNET_RPC_URL}", goerli = "${GOERLI_RPC_URL}" }

[profile.release]
optimizer = true
optimizer_runs = 10000
